// <auto-generated />
using System;
using KidsQuiz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KidsQuiz.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250523012336_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KidsQuiz.Data.Models.Kid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DynamicProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kids");
                });

            modelBuilder.Entity("KidsQuiz.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioUrl = "",
                            CorrectAnswerIndex = 1,
                            CreatedAt = new DateTime(2025, 5, 23, 1, 23, 36, 647, DateTimeKind.Utc).AddTicks(8373),
                            DifficultyLevel = 0,
                            Explanation = "2 + 3 = 5",
                            ImageUrl = "",
                            Options = "[\"4\",\"5\",\"6\",\"7\"]",
                            Points = 10,
                            QuizId = 1,
                            Text = "What is 2 + 3?"
                        },
                        new
                        {
                            Id = 2,
                            AudioUrl = "",
                            CorrectAnswerIndex = 1,
                            CreatedAt = new DateTime(2025, 5, 23, 1, 23, 36, 647, DateTimeKind.Utc).AddTicks(8376),
                            DifficultyLevel = 0,
                            Explanation = "5 - 2 = 3",
                            ImageUrl = "",
                            Options = "[\"2\",\"3\",\"4\",\"5\"]",
                            Points = 10,
                            QuizId = 1,
                            Text = "What is 5 - 2?"
                        },
                        new
                        {
                            Id = 3,
                            AudioUrl = "",
                            CorrectAnswerIndex = 2,
                            CreatedAt = new DateTime(2025, 5, 23, 1, 23, 36, 647, DateTimeKind.Utc).AddTicks(8379),
                            DifficultyLevel = 1,
                            Explanation = "4 × 2 = 8",
                            ImageUrl = "",
                            Options = "[\"6\",\"7\",\"8\",\"9\"]",
                            Points = 15,
                            QuizId = 1,
                            Text = "What is 4 × 2?"
                        },
                        new
                        {
                            Id = 4,
                            AudioUrl = "",
                            CorrectAnswerIndex = 0,
                            CreatedAt = new DateTime(2025, 5, 23, 1, 23, 36, 647, DateTimeKind.Utc).AddTicks(8420),
                            DifficultyLevel = 0,
                            Explanation = "Plants need both water and sunlight to grow properly",
                            ImageUrl = "",
                            Options = "[\"Water and sunlight\",\"Only water\",\"Only sunlight\",\"Neither water nor sunlight\"]",
                            Points = 10,
                            QuizId = 2,
                            Text = "What do plants need to grow?"
                        },
                        new
                        {
                            Id = 5,
                            AudioUrl = "",
                            CorrectAnswerIndex = 1,
                            CreatedAt = new DateTime(2025, 5, 23, 1, 23, 36, 647, DateTimeKind.Utc).AddTicks(8423),
                            DifficultyLevel = 1,
                            Explanation = "Mercury is the closest planet to the Sun in our solar system",
                            ImageUrl = "",
                            Options = "[\"Venus\",\"Mercury\",\"Mars\",\"Earth\"]",
                            Points = 15,
                            QuizId = 2,
                            Text = "What is the closest planet to the Sun?"
                        });
                });

            modelBuilder.Entity("KidsQuiz.Data.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsGeneratedByLLM")
                        .HasColumnType("bit");

                    b.Property<string>("LLMPrompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DifficultyLevel");

                    b.HasIndex("Rating");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Basic arithmetic operations for young learners",
                            CreatedAt = new DateTime(2025, 5, 23, 1, 23, 36, 647, DateTimeKind.Utc).AddTicks(8287),
                            Description = "A fun quiz to test your basic math skills!",
                            DifficultyLevel = 0,
                            EstimatedDurationMinutes = 10,
                            IsGeneratedByLLM = false,
                            LLMPrompt = "",
                            Labels = "[\"math\",\"arithmetic\",\"beginner\"]",
                            Rating = 0.0,
                            RatingCount = 0,
                            Title = "Fun Math Quiz for Kids"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Basic science concepts for curious minds",
                            CreatedAt = new DateTime(2025, 5, 23, 1, 23, 36, 647, DateTimeKind.Utc).AddTicks(8388),
                            Description = "Test your knowledge about the world around us!",
                            DifficultyLevel = 1,
                            EstimatedDurationMinutes = 15,
                            IsGeneratedByLLM = false,
                            LLMPrompt = "",
                            Labels = "[\"science\",\"nature\",\"facts\"]",
                            Rating = 0.0,
                            RatingCount = 0,
                            Title = "Amazing Science Facts"
                        });
                });

            modelBuilder.Entity("KidsQuiz.Data.Models.QuizSolvingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KidId")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeTakenInSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KidId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizSolvingRecords");
                });

            modelBuilder.Entity("KidsQuiz.Data.Models.Question", b =>
                {
                    b.HasOne("KidsQuiz.Data.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("KidsQuiz.Data.Models.QuizSolvingRecord", b =>
                {
                    b.HasOne("KidsQuiz.Data.Models.Kid", "Kid")
                        .WithMany("QuizSolvingRecords")
                        .HasForeignKey("KidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsQuiz.Data.Models.Quiz", "Quiz")
                        .WithMany("QuizSolvingRecords")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kid");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("KidsQuiz.Data.Models.Kid", b =>
                {
                    b.Navigation("QuizSolvingRecords");
                });

            modelBuilder.Entity("KidsQuiz.Data.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizSolvingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
